#!/bin/bash

echo "[TASK 1] Disable and turn off SWAP"
sed -i '/swap/d' /etc/fstab
swapoff -a

echo "[TASK 2] Stop and Disable firewall"
systemctl disable --now firewalld  >/dev/null 2>&1


# Enable ssh password authentication
echo "Enable ssh password authentication"
sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
sed -i 's/.*PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
systemctl reload sshd

# Set Root password
echo "Set root password"
echo -e "r00t\nr00t" | passwd root >/dev/null 2>&1

# Update bashrc file
echo "export TERM=xterm" >> /etc/bashrc


echo "[TASK 10] Update /etc/hosts file"
cat >>/etc/hosts<<EOF
192.168.56.11   master1.linkdev.local   master1
192.168.56.12   master2.linkdev.local   master2
192.168.56.13   master3.linkdev.local   master3
192.168.56.21   worker1.linkdev.local    worker1
192.168.56.22   worker2.linkdev.local    worker2
192.168.56.50   bastion.linkdev.local   bastion
EOF
