apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 192.168.100.75
      user: root
      port: 22
      keyPath: ~/.ssh/id_rsa
    role: controller
    #privateInterface: ens160
  - ssh:
      address: 192.168.100.76
      user: root
      port: 22
      keyPath: ~/.ssh/id_rsa
    role: controller
    #privateInterface: ens160
  - ssh:
      address: 192.168.100.77
      user: root
      port: 22
      keyPath: ~/.ssh/id_rsa
    role: controller
    #privateInterface: ens160
  - ssh:
      address: 192.168.100.78
      user: root
      port: 22
      keyPath: ~/.ssh/id_rsa
    role: worker
    #privateInterface: ens160
  - ssh:
      address: 192.168.100.79
      user: root
      port: 22
      keyPath: ~/.ssh/id_rsa
    role: worker
    #privateInterface: ens160
  k0s:
    version: v1.29.2+k0s.0
    versionChannel: stable
    dynamicConfig: false
    config:
      spec:
        api:
          externalAddress: 192.168.100.80
          sans:
          - 192.168.100.80
